### ISSUE TITLE
Combinatorial StopIteration

### ISSUE THREAD

**Issue by 691175002** [adieyal/comfyui-dynamicprompts#16]
I'm not sure if I'm using this correctly, but I'm finding that the combinatorial node will raise a StopIteration and output a blank prompt at the end of every cycle.  This seems worse than just starting over at the beginning because if you are trying to batch many runs every nth cycle will execute on a blank prompt and be wasted.

**Comment by adieyal** [comment]
strange - i'll take a look

**Comment by ali1234** [comment]
https://github.com/adieyal/comfyui-dynamicprompts/blob/584b204cc3c0aee793227479dd9bf1eabfc6b23c/nodes/sampler.py#L59-L71

This happens because you reload `self._prompts` on line 66 but then on line 68 `prompts` still points at the old one. I can't see any reason for this function to even take arguments given that they are all part of the class, and it is marked private.

**Comment by michaelLochlann** [comment]
Yeah in ComfyUI, I have { first option | second option } and it draws the first 2 images fine but then it adds an extra 3rd image which has nothing to do with my prompt. So it kinda makes it not usable unfortunately.

**Comment by L-o-z** [comment]
I have found a solution that seems to work for me (I've never written python code before so it might qualify as a quick and dirty hack, or...)

At line 68 in nodes/sampler.py, insert the following line

                prompts = self._prompts

This is just after the second try: statement that @ali1234 posted, and in fact without that comment I would not have worked this out

**Comment by adieyal** [comment]
This is now fixed in 0.2.0
